import type { Metadata } from "next";
<<<<<<< HEAD
import { Saira } from "next/font/google";
import "./globals.css";
import Header from "./components/header";

const saira = Saira({
  weight: ["300", "400", "500", "600", "700"],
=======
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
>>>>>>> 9dc0fa940014d83b99dddade8717980be279d29a
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Desafio Front end",
  description: "O objetivo deste desafio é avaliar minhas habilidades de programação",
=======
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> 9dc0fa940014d83b99dddade8717980be279d29a
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <Header />
      <body className={saira.className}>
=======
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
>>>>>>> 9dc0fa940014d83b99dddade8717980be279d29a
        {children}
      </body>
    </html>
  );
}
